[package]
name = "deus-pi"
version = "0.1.0"
authors = ["Aster <galaster@foxmail.com>"]
description = "calculate pi"
edition = "2021"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/GalAster/nqueens-rs"
exclude = ["/tests/*", "/benches/*"]

[dependencies]
dashu = "0.3.1"
